name: TargetDummy
main: com.github.neapovil.targetdummy.TargetDummy
version: 1.0.0
api-version: 1.13
author: Neapovil
website: https://github.com/Neapovil/targetdummy
depend:
  - CommandAPI
  - Citizens
permissions:
  targetdummy.command.admin:
    default: op
